using System.ComponentModel;
using Microsoft.VisualStudio.Shell;

namespace PlantUmlCommentExtension
{
    public class PlantUmlOptions : DialogPage
    {
        [Category("General")]
        [DisplayName("PlantUML JAR file path")]
        [Description("Full path to the PlantUML.jar file. NOTA. - You must have the Java runtime installed on your machine and you must have it configured and with the permissions to be able to run it.")]
        public string PlantUmlJarFilePath { get; set; }

        [Category("General")]
        [DisplayName("Output directory")]
        [Description("Directory where the files generated by PlantUML are saved.")]
        public string OutputDirectory { get; set; }

        [Category("General")]
        [DisplayName("Dpi size.")]
        [Description("DPI resolution of the generated file.")]
        [DefaultValue(300)]
        public int DpiSize { get; set; } = 300;

        [Category("General")]
        [DisplayName("PlantUML Limit Size.")]
        [Description("Maximum PlantUML file size limit.")]
        [DefaultValue(8192)]
        public int PlantUmlLimitSize { get; set; } = 8192;

        [Category("General")]
        [DisplayName("Format Output Diagram")]
        [Description("Format of the generated diagram.")]
        [DefaultValue(FormatPlantUmlOutput.Svg)]
        public FormatPlantUmlOutput FormatOutputDiagram { get; set; } = FormatPlantUmlOutput.Svg;

        [Category("General")]
        [DisplayName("Encoding PlantUML Text file")]
        [Description("Encoding used for PlantUML files (Optional).")]
        public string EncodingPlantUmlTextFile { get; set; } = "UTF-8";
    }
}